#include "../utilities/test_utils.h"

#include <atlas/random/seed.h>

#include <testkit/testkit.h>

namespace {

using atlas::DEFAULT_UNSIGNED_INT_SEED;
using atlas::MORTON_EXPAND_BITS_FINAL_MASK;
using atlas::MORTON_EXPAND_BITS_FINAL_MULTIPLIER;
using atlas::MORTON_EXPAND_BITS_FIRST_MASK;
using atlas::MORTON_EXPAND_BITS_FIRST_MULTIPLIER;
using atlas::MORTON_EXPAND_BITS_SECOND_MASK;
using atlas::MORTON_EXPAND_BITS_SECOND_MULTIPLIER;
using atlas::MORTON_EXPAND_BITS_THIRD_MASK;
using atlas::MORTON_EXPAND_BITS_THIRD_MULTIPLIER;
using atlas::RANDOM_HASH_NORMAL_SCALE_FOR_MIX;
using atlas::RANDOM_HASH_PHASE_COEFF_X;
using atlas::RANDOM_HASH_PHASE_COEFF_Y;
using atlas::RANDOM_HASH_PHASE_COEFF_Z;
using atlas::RANDOM_HASH_SALT_DIFFUSE_U1;
using atlas::RANDOM_HASH_SALT_DIFFUSE_U2;
using atlas::RANDOM_HASH_SALT_MIX;
using atlas::RANDOM_HASH_VALUE_SCALE;
using atlas::SHUFFLE_HASH_FINAL_SHIFT;
using atlas::SHUFFLE_HASH_FIRST_MULTIPLIER;
using atlas::SHUFFLE_HASH_FIRST_SHIFT;
using atlas::SHUFFLE_HASH_INDEX_OFFSET;
using atlas::SHUFFLE_HASH_SECOND_MULTIPLIER;
using atlas::SHUFFLE_HASH_SECOND_SHIFT;

} // namespace

TEST(Seed, HashConstantsRemainStable) {
    // Assert: random hash seed constants remain stable.
    EXPECT_DOUBLE_EQ(RANDOM_HASH_PHASE_COEFF_X, 12.9898);
    EXPECT_DOUBLE_EQ(RANDOM_HASH_PHASE_COEFF_Y, 78.233);
    EXPECT_DOUBLE_EQ(RANDOM_HASH_PHASE_COEFF_Z, 37.719);
    EXPECT_DOUBLE_EQ(RANDOM_HASH_VALUE_SCALE, 43758.5453);
    EXPECT_DOUBLE_EQ(RANDOM_HASH_SALT_DIFFUSE_U1, 0.31);
    EXPECT_DOUBLE_EQ(RANDOM_HASH_SALT_DIFFUSE_U2, 1.73);
    EXPECT_DOUBLE_EQ(RANDOM_HASH_SALT_MIX, 2.41);
    EXPECT_DOUBLE_EQ(RANDOM_HASH_NORMAL_SCALE_FOR_MIX, 17.0);
    EXPECT_EQ(DEFAULT_UNSIGNED_INT_SEED, 0u);
}

TEST(Seed, ShuffleHashConstantsRemainStable) {
    // Assert: shuffle hash seed constants remain stable.
    EXPECT_EQ(SHUFFLE_HASH_FIRST_SHIFT, 30);
    EXPECT_EQ(SHUFFLE_HASH_SECOND_SHIFT, 27);
    EXPECT_EQ(SHUFFLE_HASH_FINAL_SHIFT, 31);
    EXPECT_EQ(SHUFFLE_HASH_INDEX_OFFSET, 0x9e3779b97f4a7c15ull);
    EXPECT_EQ(SHUFFLE_HASH_FIRST_MULTIPLIER, 0xbf58476d1ce4e5b9ull);
    EXPECT_EQ(SHUFFLE_HASH_SECOND_MULTIPLIER, 0x94d049bb133111ebull);
}

TEST(Seed, MortonExpandBitConstantsRemainStable) {
    // Assert: Morton bit expansion constants remain stable.
    EXPECT_EQ(MORTON_EXPAND_BITS_FIRST_MULTIPLIER, 0x00010001u);
    EXPECT_EQ(MORTON_EXPAND_BITS_FIRST_MASK, 0xFF0000FFu);
    EXPECT_EQ(MORTON_EXPAND_BITS_SECOND_MULTIPLIER, 0x00000101u);
    EXPECT_EQ(MORTON_EXPAND_BITS_SECOND_MASK, 0x0F00F00Fu);
    EXPECT_EQ(MORTON_EXPAND_BITS_THIRD_MULTIPLIER, 0x00000011u);
    EXPECT_EQ(MORTON_EXPAND_BITS_THIRD_MASK, 0xC30C30C3u);
    EXPECT_EQ(MORTON_EXPAND_BITS_FINAL_MULTIPLIER, 0x00000005u);
    EXPECT_EQ(MORTON_EXPAND_BITS_FINAL_MASK, 0x49249249u);
}
