#pragma once

#include <atlas/memory/raw_pointer_cast.h>

namespace atlas::system {

template <typename T>
Measurer<T>::Measurer(UniverseHostPtr<T> universe,
                      FluidHostPtr<T> fluid,
                      SpatialHashingSearcherHostPtr<T> searcher) noexcept
    : _universe(std::move(universe))
    , _fluid(std::move(fluid))
    , _searcher(std::move(searcher)) {
    // Store the shared simulation dependencies used to construct measurement probes.
}

template <typename T>
bool
Measurer<T>::make_probe() noexcept {
    // Reset the probe so failed setup never leaves stale pointers behind.
    _probe = {};

    // All three dependencies are required to expose cell, particle, and searcher data.
    if (!_universe || !_fluid || !_searcher) {
        return false;
    }

    // Retrieve universe-side cell temperature storage.
    auto* universe_temperature
        = _universe->template state<atlas::universe::UniverseTemperatureState<T>>();

    // Retrieve universe-side cell bulk velocity storage.
    auto* universe_bulk_velocity
        = _universe->template state<atlas::universe::UniverseBulkVelocityState<T>>();

    // Retrieve universe-side cell thermal energy storage.
    auto* universe_thermal_energy
        = _universe->template state<atlas::universe::UniverseThermalEnergyState<T>>();

    // Retrieve universe-side per-cell particle count storage.
    auto* universe_number_particle
        = _universe->template state<atlas::universe::UniverseNumberParticleState<T>>();

    // Retrieve fluid-side particle velocity storage.
    auto* fluid_velocity = _fluid->template state<atlas::fluid::FluidVelocityState<T>>();

    // Retrieve optional fluid-side particle temperature storage.
    auto* fluid_temperature = _fluid->template state<atlas::fluid::FluidTemperatureState<T>>();

    // Required universe states and particle velocity state must exist before measurement.
    if (universe_temperature == nullptr || universe_bulk_velocity == nullptr
        || universe_thermal_energy == nullptr || universe_number_particle == nullptr
        || fluid_velocity == nullptr) {
        return false;
    }

    // Bind probe pointers to universe-side measured field buffers.
    _probe.field_temperature_ptr = atlas::raw_pointer_cast(universe_temperature->data().data());
    _probe.bulk_velocity_ptr     = atlas::raw_pointer_cast(universe_bulk_velocity->data().data());
    _probe.thermal_energy_ptr    = atlas::raw_pointer_cast(universe_thermal_energy->data().data());
    _probe.number_particle_ptr   = atlas::raw_pointer_cast(universe_number_particle->data().data());

    // Bind probe pointer to fluid particle velocity data.
    _probe.velocity_ptr = atlas::raw_pointer_cast(fluid_velocity->data().data());

    // Bind optional particle temperature output when the fluid state is available.
    _probe.particle_temperature_ptr = fluid_temperature != nullptr
        ? atlas::raw_pointer_cast(fluid_temperature->data().data())
        : nullptr;

    // Bind particle-to-cell indexing data generated by the spatial searcher.
    _probe.indices_ptr    = _searcher->indices();
    _probe.cell_start_ptr = _searcher->cell_start();
    _probe.cell_end_ptr   = _searcher->cell_end();

    // Store scalar metadata required by device-side measurement kernels.
    _probe.particle_count = static_cast<int>(_fluid->particle_count());
    _probe.num_of_cells   = _universe->number_of_cells();

    // Probe creation succeeds only when counts are valid and searcher buffers are bound.
    return _probe.particle_count >= 0
        && _probe.num_of_cells > 0
        && _probe.indices_ptr != nullptr
        && _probe.cell_start_ptr != nullptr
        && _probe.cell_end_ptr != nullptr;
}

} // namespace atlas::system