#pragma once
#include <atlas/math/constants.h>
#include <atlas/math/detail/config.h>
#include <atlas/math/detail/ops.h>
#include <atlas/math/matrix/matrix.h>
#include <atlas/math/matrix/matrix2x2.h>
#include <atlas/math/matrix/matrix3x3.h>
#include <atlas/math/matrix/matrix4x4.h>
#include <atlas/math/matrix/matrix_elementwise.h>
#include <atlas/math/matrix/matrix_expression.h>
#include <atlas/math/matrix/matrix_operators.h>
#include <atlas/math/matrix/matrix_reductions.h>
#include <atlas/math/matrix/matrix_statistics.h>
#include <atlas/math/quaternion.h>
#include <atlas/math/vector/vector.h>
#include <atlas/math/vector/vector2.h>
#include <atlas/math/vector/vector3.h>
#include <atlas/math/vector/vector4.h>
#include <atlas/math/vector/vector_elementwise.h>
#include <atlas/math/vector/vector_expression.h>
#include <atlas/math/vector/vector_operators.h>
#include <atlas/math/vector/vector_reductions.h>
#include <atlas/math/vector/vector_statistics.h>