name: TBB Core macOS

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  core-macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS TBB Debug
            configure_preset: tbb-debug-core
            build_preset: build-tbb-debug-core
            test_command: ctest --preset ctest-tbb-debug-core
          - name: macOS TBB Release
            configure_preset: tbb-release-core
            build_preset: build-tbb-release-core
            test_command: ctest --preset ctest-tbb-release-core
    name: ${{ matrix.name }}
    uses: ./.github/workflows/tbb-common.yml
    with:
      runner: macos-14
      run_tests: true
      install_command: |
        brew update
        brew install ninja tbb
      configure_preset: ${{ matrix.configure_preset }}
      build_preset: ${{ matrix.build_preset }}
      test_command: ${{ matrix.test_command }}
