name: TBB Common

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      install_command:
        required: true
        type: string
      configure_preset:
        required: true
        type: string
      build_preset:
        required: true
        type: string
      test_command:
        required: false
        type: string
      run_tests:
        required: true
        type: boolean

jobs:
  tbb:
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: ${{ inputs.install_command }}

      - name: Configure
        run: cmake --preset ${{ inputs.configure_preset }}

      - name: Build
        run: cmake --build --preset ${{ inputs.build_preset }}

      - name: Test
        if: ${{ inputs.run_tests }}
        run: ${{ inputs.test_command }}
