name: TBB Vizkit Linux

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  vizkit-linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu TBB Debug Vizkit Build
            configure_preset: tbb-debug
            build_preset: build-tbb-debug
          - name: Ubuntu TBB Release Vizkit Build
            configure_preset: tbb-release
            build_preset: build-tbb-release
    name: ${{ matrix.name }}
    uses: ./.github/workflows/tbb-common.yml
    with:
      runner: ubuntu-24.04
      run_tests: false
      install_command: |
        sudo apt-get update
        sudo apt-get install -y \
          ninja-build \
          libtbb-dev \
          libglfw3-dev \
          libglew-dev
      configure_preset: ${{ matrix.configure_preset }}
      build_preset: ${{ matrix.build_preset }}
